### ISSUE TITLE
Main window: Default size too large for some screens

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#577]
> Ubuntu 24.04 user with Parula v0.8.17 on a 1366x768 pixel laptop display.  Parula window size is (much) larger than screen size after every start-up.  Is this to be expected for that version? 
> 
> Not a big issue for me, but less experienced users could have hard time finding the out-of-sight preferences icon (see screen shot).
> 
> ![Image](https://github.com/user-attachments/assets/919f0f58-71f3-41ea-b28e-0616f5b4bfb7)
>  

 _Originally posted by @lenoleno in [#467](https://github.com/mustang-im/mustang/issues/467#issuecomment-2822470985)_

**Comment by benbucksch** [comment]
@lenoleno I've made a fix, which I think should be working, but I don't have such a small screen to test it with. The fix should be in the upcoming 0.8.18. Can you test it when it comes out, please?

**Comment by lenoleno** [comment]
No change in behaviour with v0.8.18, unfortunately.
Start-up window size is 1700x950 pixels vs. 1366x743 pixels, which is the correct size of the maximized window.

**Comment by lenoleno** [comment]
Since the bug is still present in v0.8.19, I suggest re-opening this issue so it doesn't get lost.

![Image](https://github.com/user-attachments/assets/4920e504-b87d-4126-96c7-86a0f6e4767d)
